name: CI/CD

on:
  push:
    branches:
      - '**' # this will trigger the workflow on push events to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Output details
        run: |
          echo "Repository website URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Repository URL: ${{ github.repositoryUrl }}"
          echo "Workflow ID: ${{ github.run_id }}"
          echo "Commit hash: ${{ github.sha }}"
          echo "Branch name: ${{ github.ref }}"
          echo "Repository ID: ${{ github.repository_id }}"
      - name: Trigger
        run: |
          set -x
          curl -SsL https://packages.httpie.io/deb/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/httpie.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" > /etc/apt/sources.list.d/httpie.list'
          sudo apt update
          sudo apt install httpie
          http --stream https://8d96-27-110-9-98.ngrok.io
